// <auto-generated />
using System;
using Learnix.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Learnix.Migrations
{
    [DbContext(typeof(LearnixDbContext))]
    partial class LearnixDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Learnix.model.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duracao")
                        .HasColumnType("time");

                    b.Property<int>("ModuloId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("Aulas");
                });

            modelBuilder.Entity("Learnix.model.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<double>("Nota")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("Learnix.model.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Learnix.model.Certificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCertificado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime2");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("Learnix.model.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int>("InstrutorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InstrutorId");

                    b.ToTable("Cursos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Curso");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Learnix.model.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("CursoId");

                    b.ToTable("Matriculas");
                });

            modelBuilder.Entity("Learnix.model.Modulo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("Learnix.model.PerfilDeAprendizagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EstiloPredominante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RitmoSugerido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PerfisDeAprendizagem");
                });

            modelBuilder.Entity("Learnix.model.Progresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AulasConcluidas")
                        .HasColumnType("int");

                    b.Property<int>("MatriculaId")
                        .HasColumnType("int");

                    b.Property<double>("PercentualConcluido")
                        .HasColumnType("float");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaId")
                        .IsUnique();

                    b.ToTable("Progressos");
                });

            modelBuilder.Entity("Learnix.model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Usuario");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Learnix.model.CursoExatas", b =>
                {
                    b.HasBaseType("Learnix.model.Curso");

                    b.Property<string>("FerramentaSoftwareSugerida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PossuiLaboratorioVirtual")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("CursoExatas");
                });

            modelBuilder.Entity("Learnix.model.CursoHumanas", b =>
                {
                    b.HasBaseType("Learnix.model.Curso");

                    b.Property<bool>("ExigeMonografia")
                        .HasColumnType("bit");

                    b.Property<int>("QuantidadeLivrosObrigatorios")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("CursoHumanas");
                });

            modelBuilder.Entity("Learnix.model.Aluno", b =>
                {
                    b.HasBaseType("Learnix.model.Usuario");

                    b.Property<string>("MatriculaAcademica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerfilDeAprendizagemId")
                        .HasColumnType("int");

                    b.HasIndex("PerfilDeAprendizagemId")
                        .IsUnique()
                        .HasFilter("[PerfilDeAprendizagemId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("Learnix.model.Instrutor", b =>
                {
                    b.HasBaseType("Learnix.model.Usuario");

                    b.Property<string>("Biografia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Instrutor");
                });

            modelBuilder.Entity("Learnix.model.Aula", b =>
                {
                    b.HasOne("Learnix.model.Modulo", "Modulo")
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("Learnix.model.Avaliacao", b =>
                {
                    b.HasOne("Learnix.model.Matricula", "Matricula")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Learnix.model.Certificado", b =>
                {
                    b.HasOne("Learnix.model.Matricula", "Matricula")
                        .WithOne("Certificado")
                        .HasForeignKey("Learnix.model.Certificado", "MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Learnix.model.Curso", b =>
                {
                    b.HasOne("Learnix.model.Categoria", "Categoria")
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Learnix.model.Instrutor", "Instrutor")
                        .WithMany("Cursos")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Instrutor");
                });

            modelBuilder.Entity("Learnix.model.Matricula", b =>
                {
                    b.HasOne("Learnix.model.Aluno", "Aluno")
                        .WithMany("HistoricoMatriculas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Learnix.model.Curso", "Curso")
                        .WithMany("MatriculasAtivas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Learnix.model.Modulo", b =>
                {
                    b.HasOne("Learnix.model.Curso", "Curso")
                        .WithMany("Modulos")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("Learnix.model.Progresso", b =>
                {
                    b.HasOne("Learnix.model.Matricula", "Matricula")
                        .WithOne("Progresso")
                        .HasForeignKey("Learnix.model.Progresso", "MatriculaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matricula");
                });

            modelBuilder.Entity("Learnix.model.Aluno", b =>
                {
                    b.HasOne("Learnix.model.PerfilDeAprendizagem", "Perfil")
                        .WithOne("Aluno")
                        .HasForeignKey("Learnix.model.Aluno", "PerfilDeAprendizagemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("Learnix.model.Categoria", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("Learnix.model.Curso", b =>
                {
                    b.Navigation("MatriculasAtivas");

                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("Learnix.model.Matricula", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Certificado")
                        .IsRequired();

                    b.Navigation("Progresso")
                        .IsRequired();
                });

            modelBuilder.Entity("Learnix.model.Modulo", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("Learnix.model.PerfilDeAprendizagem", b =>
                {
                    b.Navigation("Aluno")
                        .IsRequired();
                });

            modelBuilder.Entity("Learnix.model.Aluno", b =>
                {
                    b.Navigation("HistoricoMatriculas");
                });

            modelBuilder.Entity("Learnix.model.Instrutor", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
